.\"
.\" $Id: ngircd.conf.5,v 1.2 2002/04/02 20:19:22 alex Exp $
.\"
.TH ngircd.conf 5 "March 2002" ngircd "ngIRCd Manual"
.SH NAME
ngircd.conf \- configuration file of ngircd
.SH SYNOPSIS
.B /usr/local/etc/ngircd.conf
.SH DESCRIPTION
(coming soon)
.SH AUTHOR
Alexander Barton, <alex@barton.de>
.SH "SEE ALSO"
.BR ngircd (8)
.BR ircd (8)
.\"
.\" -eof-
