.\"
.\" $Id: ngircd.conf.5,v 1.3 2002/04/02 20:24:24 alex Exp $
.\"
.TH ngircd.conf 5 "March 2002" ngircd "ngIRCd Manual"
.SH NAME
ngircd.conf \- configuration file of ngircd
.SH SYNOPSIS
.B /usr/local/etc/ngircd.conf
.SH DESCRIPTION
(coming soon)
.SH AUTHOR
Alexander Barton,
.UR mailto:alex@barton.de
alex@barton.de
.UE
.PP
Homepage:
.UR http://arthur.ath.cx/~alex/ngircd/
http://arthur.ath.cx/~alex/ngircd/
.UE
.SH "SEE ALSO"
.BR ngircd (8)
.BR ircd (8)
.\"
.\" -eof-
