.\"
.\" $Id: ngircd.8,v 1.5 2002/11/18 18:49:34 alex Exp $
.\"
.TH ngircd 8 "September 2002" ngircd "ngIRCd Manual"
.SH NAME
ngircd \- the next generation IRC daemon
.SH SYNOPSIS
.B ngircd [
.I Options
.B ]
.SH DESCRIPTION
.B ngircd
is a portable IRC daemon written from scratch. It is easy to configure,
supports server links (even with original ircds) and runs on hosts with
changing IP addresses (such as dial-in networks). Currently supported
platforms (tested versions) are: AIX (3.2.5), A/UX (3.0.1), FreeBSD
(4.5), HP-UX (10.20), IRIX (6.5), Linux (2.x), Mac OS X (10.x), NetBSD
(1.5.2/i386, 1.5.3/m68k), Solaris (2.5.1, 2.6), and Windows with Cygwin.
.SH OPTIONS
.IP --configtest
read, validate and display configuration; then exit.
.IP "-f file, --config file"
use
.I file
as configuration file.
.IP "-n, --nodaemon"
don't fork and don't detach from controlling terminal.
.IP "-p, --passive"
disable automatic connections to other servers.
.IP --version
output version information and exit.
.IP --help
display brief help text and exit.
.SH FILES
.I /usr/local/etc/ngircd.conf
.RS
The system wide default configuration file.
.SH AUTHOR
Alexander Barton,
.UR mailto:alex@barton.de
alex@barton.de
.UE
.br
Homepage:
.UR http://arthur.ath.cx/~alex/ngircd/
http://arthur.ath.cx/~alex/ngircd/
.UE
.SH "SEE ALSO"
.BR ngircd.conf (5),
.BR ircd (8)
.\"
.\" -eof-
